// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/datastore/interfaces/connection.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gocql "github.com/gocql/gocql"
	gomock "github.com/golang/mock/gomock"
	interfaces "github.com/trigg3rX/triggerx-backend/pkg/datastore/interfaces"
)

// MockConnection is a mock of Connection interface.
type MockConnection struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionMockRecorder
}

// MockConnectionMockRecorder is the mock recorder for MockConnection.
type MockConnectionMockRecorder struct {
	mock *MockConnection
}

// NewMockConnection creates a new mock instance.
func NewMockConnection(ctrl *gomock.Controller) *MockConnection {
	mock := &MockConnection{ctrl: ctrl}
	mock.recorder = &MockConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnection) EXPECT() *MockConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConnection) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConnection)(nil).Close))
}

// GetGocqlxSession mocks base method.
func (m *MockConnection) GetGocqlxSession() interfaces.GocqlxSessioner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGocqlxSession")
	ret0, _ := ret[0].(interfaces.GocqlxSessioner)
	return ret0
}

// GetGocqlxSession indicates an expected call of GetGocqlxSession.
func (mr *MockConnectionMockRecorder) GetGocqlxSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGocqlxSession", reflect.TypeOf((*MockConnection)(nil).GetGocqlxSession))
}

// GetSession mocks base method.
func (m *MockConnection) GetSession() interfaces.Sessioner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession")
	ret0, _ := ret[0].(interfaces.Sessioner)
	return ret0
}

// GetSession indicates an expected call of GetSession.
func (mr *MockConnectionMockRecorder) GetSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockConnection)(nil).GetSession))
}

// HealthCheck mocks base method.
func (m *MockConnection) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockConnectionMockRecorder) HealthCheck(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockConnection)(nil).HealthCheck), ctx)
}

// MockSessioner is a mock of Sessioner interface.
type MockSessioner struct {
	ctrl     *gomock.Controller
	recorder *MockSessionerMockRecorder
}

// MockSessionerMockRecorder is the mock recorder for MockSessioner.
type MockSessionerMockRecorder struct {
	mock *MockSessioner
}

// NewMockSessioner creates a new mock instance.
func NewMockSessioner(ctrl *gomock.Controller) *MockSessioner {
	mock := &MockSessioner{ctrl: ctrl}
	mock.recorder = &MockSessionerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessioner) EXPECT() *MockSessionerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSessioner) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockSessionerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSessioner)(nil).Close))
}

// Query mocks base method.
func (m *MockSessioner) Query(stmt string, values ...interface{}) *gocql.Query {
	m.ctrl.T.Helper()
	varargs := []interface{}{stmt}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(*gocql.Query)
	return ret0
}

// Query indicates an expected call of Query.
func (mr *MockSessionerMockRecorder) Query(stmt interface{}, values ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{stmt}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockSessioner)(nil).Query), varargs...)
}

// MockQuery is a mock of Query interface.
type MockQuery struct {
	ctrl     *gomock.Controller
	recorder *MockQueryMockRecorder
}

// MockQueryMockRecorder is the mock recorder for MockQuery.
type MockQueryMockRecorder struct {
	mock *MockQuery
}

// NewMockQuery creates a new mock instance.
func NewMockQuery(ctrl *gomock.Controller) *MockQuery {
	mock := &MockQuery{ctrl: ctrl}
	mock.recorder = &MockQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuery) EXPECT() *MockQueryMockRecorder {
	return m.recorder
}

// BindStruct mocks base method.
func (m *MockQuery) BindStruct(data interface{}) interfaces.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindStruct", data)
	ret0, _ := ret[0].(interfaces.Query)
	return ret0
}

// BindStruct indicates an expected call of BindStruct.
func (mr *MockQueryMockRecorder) BindStruct(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindStruct", reflect.TypeOf((*MockQuery)(nil).BindStruct), data)
}

// Exec mocks base method.
func (m *MockQuery) Exec() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec")
	ret0, _ := ret[0].(error)
	return ret0
}

// Exec indicates an expected call of Exec.
func (mr *MockQueryMockRecorder) Exec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockQuery)(nil).Exec))
}

// Iter mocks base method.
func (m *MockQuery) Iter() interfaces.Iter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Iter")
	ret0, _ := ret[0].(interfaces.Iter)
	return ret0
}

// Iter indicates an expected call of Iter.
func (mr *MockQueryMockRecorder) Iter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Iter", reflect.TypeOf((*MockQuery)(nil).Iter))
}

// Scan mocks base method.
func (m *MockQuery) Scan(dest ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockQueryMockRecorder) Scan(dest ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockQuery)(nil).Scan), dest...)
}

// WithContext mocks base method.
func (m *MockQuery) WithContext(ctx context.Context) interfaces.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithContext", ctx)
	ret0, _ := ret[0].(interfaces.Query)
	return ret0
}

// WithContext indicates an expected call of WithContext.
func (mr *MockQueryMockRecorder) WithContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithContext", reflect.TypeOf((*MockQuery)(nil).WithContext), ctx)
}

// MockIter is a mock of Iter interface.
type MockIter struct {
	ctrl     *gomock.Controller
	recorder *MockIterMockRecorder
}

// MockIterMockRecorder is the mock recorder for MockIter.
type MockIterMockRecorder struct {
	mock *MockIter
}

// NewMockIter creates a new mock instance.
func NewMockIter(ctrl *gomock.Controller) *MockIter {
	mock := &MockIter{ctrl: ctrl}
	mock.recorder = &MockIterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIter) EXPECT() *MockIterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIter)(nil).Close))
}

// Scan mocks base method.
func (m *MockIter) Scan(dest ...interface{}) bool {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockIterMockRecorder) Scan(dest ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockIter)(nil).Scan), dest...)
}

// MockGocqlxSessioner is a mock of GocqlxSessioner interface.
type MockGocqlxSessioner struct {
	ctrl     *gomock.Controller
	recorder *MockGocqlxSessionerMockRecorder
}

// MockGocqlxSessionerMockRecorder is the mock recorder for MockGocqlxSessioner.
type MockGocqlxSessionerMockRecorder struct {
	mock *MockGocqlxSessioner
}

// NewMockGocqlxSessioner creates a new mock instance.
func NewMockGocqlxSessioner(ctrl *gomock.Controller) *MockGocqlxSessioner {
	mock := &MockGocqlxSessioner{ctrl: ctrl}
	mock.recorder = &MockGocqlxSessionerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGocqlxSessioner) EXPECT() *MockGocqlxSessionerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockGocqlxSessioner) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockGocqlxSessionerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockGocqlxSessioner)(nil).Close))
}

// Query mocks base method.
func (m *MockGocqlxSessioner) Query(stmt string, names []string) interfaces.GocqlxQueryer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", stmt, names)
	ret0, _ := ret[0].(interfaces.GocqlxQueryer)
	return ret0
}

// Query indicates an expected call of Query.
func (mr *MockGocqlxSessionerMockRecorder) Query(stmt, names interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockGocqlxSessioner)(nil).Query), stmt, names)
}

// RawSession mocks base method.
func (m *MockGocqlxSessioner) RawSession() interfaces.Sessioner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RawSession")
	ret0, _ := ret[0].(interfaces.Sessioner)
	return ret0
}

// RawSession indicates an expected call of RawSession.
func (mr *MockGocqlxSessionerMockRecorder) RawSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawSession", reflect.TypeOf((*MockGocqlxSessioner)(nil).RawSession))
}
