// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/datastore/interfaces/connection.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	interfaces "github.com/trigg3rX/triggerx-backend/pkg/datastore/interfaces"
)

// MockGocqlxQueryer is a mock of GocqlxQueryer interface.
type MockGocqlxQueryer struct {
	ctrl     *gomock.Controller
	recorder *MockGocqlxQueryerMockRecorder
}

// MockGocqlxQueryerMockRecorder is the mock recorder for MockGocqlxQueryer.
type MockGocqlxQueryerMockRecorder struct {
	mock *MockGocqlxQueryer
}

// NewMockGocqlxQueryer creates a new mock instance.
func NewMockGocqlxQueryer(ctrl *gomock.Controller) *MockGocqlxQueryer {
	mock := &MockGocqlxQueryer{ctrl: ctrl}
	mock.recorder = &MockGocqlxQueryerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGocqlxQueryer) EXPECT() *MockGocqlxQueryerMockRecorder {
	return m.recorder
}

// BindStruct mocks base method.
func (m *MockGocqlxQueryer) BindStruct(data interface{}) interfaces.GocqlxQueryer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindStruct", data)
	ret0, _ := ret[0].(interfaces.GocqlxQueryer)
	return ret0
}

// BindStruct indicates an expected call of BindStruct.
func (mr *MockGocqlxQueryerMockRecorder) BindStruct(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindStruct", reflect.TypeOf((*MockGocqlxQueryer)(nil).BindStruct), data)
}

// ExecRelease mocks base method.
func (m *MockGocqlxQueryer) ExecRelease() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecRelease")
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecRelease indicates an expected call of ExecRelease.
func (mr *MockGocqlxQueryerMockRecorder) ExecRelease() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecRelease", reflect.TypeOf((*MockGocqlxQueryer)(nil).ExecRelease))
}

// GetRelease mocks base method.
func (m *MockGocqlxQueryer) GetRelease(dest interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelease", dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetRelease indicates an expected call of GetRelease.
func (mr *MockGocqlxQueryerMockRecorder) GetRelease(dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelease", reflect.TypeOf((*MockGocqlxQueryer)(nil).GetRelease), dest)
}

// Select mocks base method.
func (m *MockGocqlxQueryer) Select(dest interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Select indicates an expected call of Select.
func (mr *MockGocqlxQueryerMockRecorder) Select(dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockGocqlxQueryer)(nil).Select), dest)
}

// SelectRelease mocks base method.
func (m *MockGocqlxQueryer) SelectRelease(dest interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectRelease", dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// SelectRelease indicates an expected call of SelectRelease.
func (mr *MockGocqlxQueryerMockRecorder) SelectRelease(dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectRelease", reflect.TypeOf((*MockGocqlxQueryer)(nil).SelectRelease), dest)
}

// WithContext mocks base method.
func (m *MockGocqlxQueryer) WithContext(ctx context.Context) interfaces.GocqlxQueryer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithContext", ctx)
	ret0, _ := ret[0].(interfaces.GocqlxQueryer)
	return ret0
}

// WithContext indicates an expected call of WithContext.
func (mr *MockGocqlxQueryerMockRecorder) WithContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithContext", reflect.TypeOf((*MockGocqlxQueryer)(nil).WithContext), ctx)
}
