// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/datastore/interfaces/query_builder.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockScyllaQueryBuilder is a mock of ScyllaQueryBuilder interface.
type MockScyllaQueryBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockScyllaQueryBuilderMockRecorder
}

// MockScyllaQueryBuilderMockRecorder is the mock recorder for MockScyllaQueryBuilder.
type MockScyllaQueryBuilderMockRecorder struct {
	mock *MockScyllaQueryBuilder
}

// NewMockScyllaQueryBuilder creates a new mock instance.
func NewMockScyllaQueryBuilder(ctrl *gomock.Controller) *MockScyllaQueryBuilder {
	mock := &MockScyllaQueryBuilder{ctrl: ctrl}
	mock.recorder = &MockScyllaQueryBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScyllaQueryBuilder) EXPECT() *MockScyllaQueryBuilderMockRecorder {
	return m.recorder
}

// BatchInsert mocks base method.
func (m *MockScyllaQueryBuilder) BatchInsert(ctx context.Context, data []interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsert", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInsert indicates an expected call of BatchInsert.
func (mr *MockScyllaQueryBuilderMockRecorder) BatchInsert(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsert", reflect.TypeOf((*MockScyllaQueryBuilder)(nil).BatchInsert), ctx, data)
}

// Close mocks base method.
func (m *MockScyllaQueryBuilder) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockScyllaQueryBuilderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockScyllaQueryBuilder)(nil).Close))
}

// Delete mocks base method.
func (m *MockScyllaQueryBuilder) Delete(ctx context.Context, data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockScyllaQueryBuilderMockRecorder) Delete(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockScyllaQueryBuilder)(nil).Delete), ctx, data)
}

// Get mocks base method.
func (m *MockScyllaQueryBuilder) Get(ctx context.Context, data interface{}) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, data)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockScyllaQueryBuilderMockRecorder) Get(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockScyllaQueryBuilder)(nil).Get), ctx, data)
}

// Insert mocks base method.
func (m *MockScyllaQueryBuilder) Insert(ctx context.Context, data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockScyllaQueryBuilderMockRecorder) Insert(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockScyllaQueryBuilder)(nil).Insert), ctx, data)
}

// Select mocks base method.
func (m *MockScyllaQueryBuilder) Select(ctx context.Context, data interface{}) ([]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, data)
	ret0, _ := ret[0].([]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockScyllaQueryBuilderMockRecorder) Select(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockScyllaQueryBuilder)(nil).Select), ctx, data)
}

// SelectAll mocks base method.
func (m *MockScyllaQueryBuilder) SelectAll(ctx context.Context) ([]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAll", ctx)
	ret0, _ := ret[0].([]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAll indicates an expected call of SelectAll.
func (mr *MockScyllaQueryBuilderMockRecorder) SelectAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAll", reflect.TypeOf((*MockScyllaQueryBuilder)(nil).SelectAll), ctx)
}

// SetBatchSize mocks base method.
func (m *MockScyllaQueryBuilder) SetBatchSize(size int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBatchSize", size)
}

// SetBatchSize indicates an expected call of SetBatchSize.
func (mr *MockScyllaQueryBuilderMockRecorder) SetBatchSize(size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBatchSize", reflect.TypeOf((*MockScyllaQueryBuilder)(nil).SetBatchSize), size)
}

// SetConsistencyLevel mocks base method.
func (m *MockScyllaQueryBuilder) SetConsistencyLevel(level string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConsistencyLevel", level)
}

// SetConsistencyLevel indicates an expected call of SetConsistencyLevel.
func (mr *MockScyllaQueryBuilderMockRecorder) SetConsistencyLevel(level interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConsistencyLevel", reflect.TypeOf((*MockScyllaQueryBuilder)(nil).SetConsistencyLevel), level)
}

// Update mocks base method.
func (m *MockScyllaQueryBuilder) Update(ctx context.Context, data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockScyllaQueryBuilderMockRecorder) Update(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScyllaQueryBuilder)(nil).Update), ctx, data)
}
