FROM golang:1.23-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache gcc musl-dev

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o dbserver ./cmd/dbserver

# Create a minimal runtime image
FROM alpine:latest
WORKDIR /app
COPY --from=0 /app/dbserver .
COPY .env .

# Run the server
CMD ["./dbserver"] 