services:
  scylla:
    image: scylladb/scylla
    container_name: triggerx-scylla
    ports:
      - "${DATABASE_HOST_PORT}:9042"
    volumes:
      - scylla_data:/var/lib/scylla
    logging:
      driver: "json-file"

  # redis:
  #   image: "redis:7-alpine"
  #   container_name: triggerx-redis
  #   ports:
  #     - "6379:6379"

volumes:
  scylla_data: 