services:
  scylla:
    image: scylladb/scylla
    container_name: triggerx-scylla
    ports:
      - "${DATABASE_DOCKER_PORT}:9042"
    volumes:
      - scylla_data:/var/lib/scylla
    logging:
      driver: "json-file"

volumes:
  scylla_data: 