x-othentic-cli: &othentic-cli
  env_file:
    - .env
  build:
    context: .
    dockerfile: ./Dockerfile

services:
  scylla:
    image: scylladb/scylla
    container_name: triggerx-scylla
    ports:
      - "${DATABASE_DOCKER_PORT}:9042"
    volumes:
      - scylla_data:/var/lib/scylla
    command: --smp 1 --memory 512M --overprovisioned 1
    logging:
      driver: "json-file"

volumes:
  scylla_data: 