FROM golang:1.22-alpine AS builder

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o loadbalancer ./cmd/loadbalancer

# Use a smaller image for the final container
FROM alpine:3.18

WORKDIR /app

# Copy the binary from builder
COPY --from=builder /app/loadbalancer .

# Expose the port
EXPOSE 8080

# Run the application
CMD ["./loadbalancer"] 