services:
  scylla:
    profiles: [scylla]
    image: scylladb/scylla
    container_name: triggerx-scylla
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla
    logging:
      driver: "json-file"
    networks:
      - triggerx-network

  otel-collector:
    profiles: [lgtm]
    image: otel/opentelemetry-collector-contrib:0.96.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./../config/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    depends_on:
      - loki
      - tempo
      - mimir
    networks:
      - triggerx-obs

  loki:
    profiles: [lgtm]
    image: grafana/loki:latest
    command: -config.file=/etc/loki.yaml
    volumes:
      - ./../config/loki.yaml:/etc/loki.yaml
      - loki-data:/loki
    ports:
      - "3100:3100"
    networks:
      - triggerx-obs

  tempo:
    profiles: [lgtm]
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo.yaml
    volumes:
      - ./../config/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"
    networks:
      - triggerx-obs

  mimir:
    profiles: [lgtm]
    image: grafana/mimir:latest
    command: -config.file=/etc/mimir.yaml -target=all
    volumes:
      - ./../config/mimir.yaml:/etc/mimir.yaml
      - mimir-data:/mimir
    ports:
      - "9090:9090"
    networks:
      - triggerx-obs

  grafana:
    profiles: [lgtm]
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./../config/grafana/provisioning/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - loki
      - tempo
      - mimir
    networks:
      - triggerx-obs

  redis:
    profiles: [redis]
    image: "redis:7-alpine"
    container_name: triggerx-redis
    ports:
      - "6379:6379"

networks:
  triggerx-network:
    driver: bridge
  triggerx-obs:
    driver: bridge

volumes:
  scylla_data:
  loki-data:
  tempo-data:
  mimir-data:
  grafana-data:
