version: '3'

services:
  scylla:
    image: scylladb/scylla
    container_name: triggerx-scylla
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla
    command: --smp 1 --memory 1024M --overprovisioned 1
    logging:
      driver: "json-file"

volumes:
  scylla_data: 
