multitenancy_enabled: false

target: all

server:
  http_listen_port: 9090

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /mimir

distributor:
  pool:
    health_check_ingesters: false
  ha_tracker:
    enable_ha_tracker: false

ingester:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1

blocks_storage:
  storage_prefix: blocks
  tsdb:
    dir: /mimir/tsdb

limits:
  max_label_names_per_series: 50
  ingestion_rate: 10000
  ingestion_burst_size: 20000
