global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
      
  - job_name: 'othentic-cli'
    static_configs:
      - targets: ['localhost:7070']  # This is usually Docker's default bridge IP
      
  - job_name: 'triggerx-keepers'
    scrape_interval: 15s
    static_configs:
      - targets: ['157.173.218.229:8081']  # Using a different port for keeper metrics
      
