// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// source: pkg/rpc/proto/health.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// HealthServiceClient is the client API for HealthService service.
type HealthServiceClient interface {
	// GetActivePerformers returns active keepers for task assignment
	GetActivePerformers(ctx context.Context, in *GetActivePerformersRequest, opts ...grpc.CallOption) (*GetActivePerformersResponse, error)
	// GetNextPerformer returns the next keeper using load balancing
	GetNextPerformer(ctx context.Context, in *GetNextPerformerRequest, opts ...grpc.CallOption) (*GetNextPerformerResponse, error)
	// GetKeeperStatus returns the status of all keepers
	GetKeeperStatus(ctx context.Context, in *GetKeeperStatusRequest, opts ...grpc.CallOption) (*GetKeeperStatusResponse, error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) GetActivePerformers(ctx context.Context, in *GetActivePerformersRequest, opts ...grpc.CallOption) (*GetActivePerformersResponse, error) {
	out := new(GetActivePerformersResponse)
	err := c.cc.Invoke(ctx, "/rpc.HealthService/GetActivePerformers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetNextPerformer(ctx context.Context, in *GetNextPerformerRequest, opts ...grpc.CallOption) (*GetNextPerformerResponse, error) {
	out := new(GetNextPerformerResponse)
	err := c.cc.Invoke(ctx, "/rpc.HealthService/GetNextPerformer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetKeeperStatus(ctx context.Context, in *GetKeeperStatusRequest, opts ...grpc.CallOption) (*GetKeeperStatusResponse, error) {
	out := new(GetKeeperStatusResponse)
	err := c.cc.Invoke(ctx, "/rpc.HealthService/GetKeeperStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServiceServer is the server API for HealthService service.
type HealthServiceServer interface {
	// GetActivePerformers returns active keepers for task assignment
	GetActivePerformers(context.Context, *GetActivePerformersRequest) (*GetActivePerformersResponse, error)
	// GetNextPerformer returns the next keeper using load balancing
	GetNextPerformer(context.Context, *GetNextPerformerRequest) (*GetNextPerformerResponse, error)
	// GetKeeperStatus returns the status of all keepers
	GetKeeperStatus(context.Context, *GetKeeperStatusRequest) (*GetKeeperStatusResponse, error)
}

// UnimplementedHealthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHealthServiceServer struct {
}

func (UnimplementedHealthServiceServer) GetActivePerformers(context.Context, *GetActivePerformersRequest) (*GetActivePerformersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivePerformers not implemented")
}

func (UnimplementedHealthServiceServer) GetNextPerformer(context.Context, *GetNextPerformerRequest) (*GetNextPerformerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextPerformer not implemented")
}

func (UnimplementedHealthServiceServer) GetKeeperStatus(context.Context, *GetKeeperStatusRequest) (*GetKeeperStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeeperStatus not implemented")
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_GetActivePerformers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivePerformersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetActivePerformers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.HealthService/GetActivePerformers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetActivePerformers(ctx, req.(*GetActivePerformersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetNextPerformer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNextPerformerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetNextPerformer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.HealthService/GetNextPerformer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetNextPerformer(ctx, req.(*GetNextPerformerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetKeeperStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeeperStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetKeeperStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.HealthService/GetKeeperStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetKeeperStatus(ctx, req.(*GetKeeperStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActivePerformers",
			Handler:    _HealthService_GetActivePerformers_Handler,
		},
		{
			MethodName: "GetNextPerformer",
			Handler:    _HealthService_GetNextPerformer_Handler,
		},
		{
			MethodName: "GetKeeperStatus",
			Handler:    _HealthService_GetKeeperStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/rpc/proto/health.proto",
}
