// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// source: pkg/rpc/proto/health.proto

package proto

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// GetActivePerformersRequest requests active performers
type GetActivePerformersRequest struct {
	IncludeImua bool  `protobuf:"varint,1,opt,name=include_imua,json=includeImua,proto3" json:"include_imua,omitempty"`
	Limit       int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

// GetActivePerformersResponse returns active performers
type GetActivePerformersResponse struct {
	Performers []*Performer           `protobuf:"bytes,1,rep,name=performers,proto3" json:"performers,omitempty"`
	Count      int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

// GetNextPerformerRequest requests the next performer (load balanced)
type GetNextPerformerRequest struct {
	IsImuaTask bool   `protobuf:"varint,1,opt,name=is_imua_task,json=isImuaTask,proto3" json:"is_imua_task,omitempty"`
	TaskType   string `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
}

// GetNextPerformerResponse returns the selected performer
type GetNextPerformerResponse struct {
	Performer *Performer `protobuf:"bytes,1,opt,name=performer,proto3" json:"performer,omitempty"`
	Strategy  string     `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
}

// GetKeeperStatusRequest requests keeper status information
type GetKeeperStatusRequest struct {
	KeeperAddresses []string `protobuf:"bytes,1,rep,name=keeper_addresses,json=keeperAddresses,proto3" json:"keeper_addresses,omitempty"`
}

// GetKeeperStatusResponse returns keeper status
type GetKeeperStatusResponse struct {
	Keepers       []*KeeperInfo          `protobuf:"bytes,1,rep,name=keepers,proto3" json:"keepers,omitempty"`
	TotalKeepers  int32                  `protobuf:"varint,2,opt,name=total_keepers,json=totalKeepers,proto3" json:"total_keepers,omitempty"`
	ActiveKeepers int32                  `protobuf:"varint,3,opt,name=active_keepers,json=activeKeepers,proto3" json:"active_keepers,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

// Performer represents a keeper available for task execution
type Performer struct {
	OperatorId    int64                  `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	KeeperAddress string                 `protobuf:"bytes,2,opt,name=keeper_address,json=keeperAddress,proto3" json:"keeper_address,omitempty"`
	IsImua        bool                   `protobuf:"varint,3,opt,name=is_imua,json=isImua,proto3" json:"is_imua,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
}

// KeeperInfo represents detailed keeper information
type KeeperInfo struct {
	KeeperName       string                 `protobuf:"bytes,1,opt,name=keeper_name,json=keeperName,proto3" json:"keeper_name,omitempty"`
	KeeperAddress    string                 `protobuf:"bytes,2,opt,name=keeper_address,json=keeperAddress,proto3" json:"keeper_address,omitempty"`
	ConsensusAddress string                 `protobuf:"bytes,3,opt,name=consensus_address,json=consensusAddress,proto3" json:"consensus_address,omitempty"`
	OperatorId       string                 `protobuf:"bytes,4,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Version          string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	IsActive         bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsImua           bool                   `protobuf:"varint,7,opt,name=is_imua,json=isImua,proto3" json:"is_imua,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	LastCheckedIn    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_checked_in,json=lastCheckedIn,proto3" json:"last_checked_in,omitempty"`
}

// Reset implementations
func (x *GetActivePerformersRequest) Reset()  { *x = GetActivePerformersRequest{} }
func (x *GetActivePerformersResponse) Reset() { *x = GetActivePerformersResponse{} }
func (x *GetNextPerformerRequest) Reset()     { *x = GetNextPerformerRequest{} }
func (x *GetNextPerformerResponse) Reset()    { *x = GetNextPerformerResponse{} }
func (x *GetKeeperStatusRequest) Reset()      { *x = GetKeeperStatusRequest{} }
func (x *GetKeeperStatusResponse) Reset()     { *x = GetKeeperStatusResponse{} }
func (x *Performer) Reset()                   { *x = Performer{} }
func (x *KeeperInfo) Reset()                  { *x = KeeperInfo{} }

// String implementations
func (x *GetActivePerformersRequest) String() string  { return "GetActivePerformersRequest{}" }
func (x *GetActivePerformersResponse) String() string { return "GetActivePerformersResponse{}" }
func (x *GetNextPerformerRequest) String() string     { return "GetNextPerformerRequest{}" }
func (x *GetNextPerformerResponse) String() string    { return "GetNextPerformerResponse{}" }
func (x *GetKeeperStatusRequest) String() string      { return "GetKeeperStatusRequest{}" }
func (x *GetKeeperStatusResponse) String() string     { return "GetKeeperStatusResponse{}" }
func (x *Performer) String() string                   { return "Performer{}" }
func (x *KeeperInfo) String() string                  { return "KeeperInfo{}" }

// ProtoMessage implementations
func (*GetActivePerformersRequest) ProtoMessage()  {}
func (*GetActivePerformersResponse) ProtoMessage() {}
func (*GetNextPerformerRequest) ProtoMessage()     {}
func (*GetNextPerformerResponse) ProtoMessage()    {}
func (*GetKeeperStatusRequest) ProtoMessage()      {}
func (*GetKeeperStatusResponse) ProtoMessage()     {}
func (*Performer) ProtoMessage()                   {}
func (*KeeperInfo) ProtoMessage()                  {}
