// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: pkg/rpc/proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceInfo represents information about an RPC service
type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Health        *HealthStatus          `protobuf:"bytes,7,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServiceInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ServiceInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *ServiceInfo) GetHealth() *HealthStatus {
	if x != nil {
		return x.Health
	}
	return nil
}

// HealthStatus represents the health status of a service
type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "unhealthy", "degraded"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *HealthStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthStatus) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthStatus) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// RPCMethod represents an RPC method definition
type RPCMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	RequestType   string                 `protobuf:"bytes,3,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
	ResponseType  string                 `protobuf:"bytes,4,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	TimeoutNanos  int64                  `protobuf:"varint,5,opt,name=timeout_nanos,json=timeoutNanos,proto3" json:"timeout_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCMethod) Reset() {
	*x = RPCMethod{}
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCMethod) ProtoMessage() {}

func (x *RPCMethod) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCMethod.ProtoReflect.Descriptor instead.
func (*RPCMethod) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *RPCMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RPCMethod) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RPCMethod) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *RPCMethod) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *RPCMethod) GetTimeoutNanos() int64 {
	if x != nil {
		return x.TimeoutNanos
	}
	return 0
}

// RPCRequest represents a generic RPC request
type RPCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCRequest) Reset() {
	*x = RPCRequest{}
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCRequest) ProtoMessage() {}

func (x *RPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCRequest.ProtoReflect.Descriptor instead.
func (*RPCRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *RPCRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RPCRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RPCRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RPCResponse represents a generic RPC response
type RPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *anypb.Any             `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCResponse) Reset() {
	*x = RPCResponse{}
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCResponse) ProtoMessage() {}

func (x *RPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCResponse.ProtoReflect.Descriptor instead.
func (*RPCResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *RPCResponse) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RPCResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RPCResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// HealthCheckRequest represents a health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// HealthCheckResponse represents a health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *HealthStatus          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetStatus() *HealthStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// GetMethodsResponse returns available RPC methods
type GetMethodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []*RPCMethod           `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMethodsResponse) Reset() {
	*x = GetMethodsResponse{}
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMethodsResponse) ProtoMessage() {}

func (x *GetMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMethodsResponse.ProtoReflect.Descriptor instead.
func (*GetMethodsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetMethodsResponse) GetMethods() []*RPCMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

var File_pkg_rpc_proto_service_proto protoreflect.FileDescriptor

const file_pkg_rpc_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/rpc/proto/service.proto\x12\x03rpc\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc6\x02\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12:\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1e.rpc.ServiceInfo.MetadataEntryR\bmetadata\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12)\n" +
	"\x06health\x18\a \x01(\v2\x11.rpc.HealthStatusR\x06health\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf0\x01\n" +
	"\fHealthStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x128\n" +
	"\adetails\x18\x04 \x03(\v2\x1e.rpc.HealthStatus.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x01\n" +
	"\tRPCMethod\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\frequest_type\x18\x03 \x01(\tR\vrequestType\x12#\n" +
	"\rresponse_type\x18\x04 \x01(\tR\fresponseType\x12#\n" +
	"\rtimeout_nanos\x18\x05 \x01(\x03R\ftimeoutNanos\"\xcc\x01\n" +
	"\n" +
	"RPCRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\apayload\x129\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1d.rpc.RPCRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xca\x01\n" +
	"\vRPCResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12:\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1e.rpc.RPCResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"@\n" +
	"\x13HealthCheckResponse\x12)\n" +
	"\x06status\x18\x01 \x01(\v2\x11.rpc.HealthStatusR\x06status\">\n" +
	"\x12GetMethodsResponse\x12(\n" +
	"\amethods\x18\x01 \x03(\v2\x0e.rpc.RPCMethodR\amethods2\xbc\x01\n" +
	"\x0eGenericService\x12)\n" +
	"\x04Call\x12\x0f.rpc.RPCRequest\x1a\x10.rpc.RPCResponse\x12@\n" +
	"\vHealthCheck\x12\x17.rpc.HealthCheckRequest\x1a\x18.rpc.HealthCheckResponse\x12=\n" +
	"\n" +
	"GetMethods\x12\x16.google.protobuf.Empty\x1a\x17.rpc.GetMethodsResponseB4Z2github.com/trigg3rX/triggerx-backend/pkg/rpc/protob\x06proto3"

var (
	file_pkg_rpc_proto_service_proto_rawDescOnce sync.Once
	file_pkg_rpc_proto_service_proto_rawDescData []byte
)

func file_pkg_rpc_proto_service_proto_rawDescGZIP() []byte {
	file_pkg_rpc_proto_service_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_proto_service_proto_rawDesc), len(file_pkg_rpc_proto_service_proto_rawDesc)))
	})
	return file_pkg_rpc_proto_service_proto_rawDescData
}

var file_pkg_rpc_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_rpc_proto_service_proto_goTypes = []any{
	(*ServiceInfo)(nil),           // 0: rpc.ServiceInfo
	(*HealthStatus)(nil),          // 1: rpc.HealthStatus
	(*RPCMethod)(nil),             // 2: rpc.RPCMethod
	(*RPCRequest)(nil),            // 3: rpc.RPCRequest
	(*RPCResponse)(nil),           // 4: rpc.RPCResponse
	(*HealthCheckRequest)(nil),    // 5: rpc.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 6: rpc.HealthCheckResponse
	(*GetMethodsResponse)(nil),    // 7: rpc.GetMethodsResponse
	nil,                           // 8: rpc.ServiceInfo.MetadataEntry
	nil,                           // 9: rpc.HealthStatus.DetailsEntry
	nil,                           // 10: rpc.RPCRequest.MetadataEntry
	nil,                           // 11: rpc.RPCResponse.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 13: google.protobuf.Any
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_pkg_rpc_proto_service_proto_depIdxs = []int32{
	8,  // 0: rpc.ServiceInfo.metadata:type_name -> rpc.ServiceInfo.MetadataEntry
	12, // 1: rpc.ServiceInfo.last_seen:type_name -> google.protobuf.Timestamp
	1,  // 2: rpc.ServiceInfo.health:type_name -> rpc.HealthStatus
	12, // 3: rpc.HealthStatus.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 4: rpc.HealthStatus.details:type_name -> rpc.HealthStatus.DetailsEntry
	13, // 5: rpc.RPCRequest.payload:type_name -> google.protobuf.Any
	10, // 6: rpc.RPCRequest.metadata:type_name -> rpc.RPCRequest.MetadataEntry
	13, // 7: rpc.RPCResponse.result:type_name -> google.protobuf.Any
	11, // 8: rpc.RPCResponse.metadata:type_name -> rpc.RPCResponse.MetadataEntry
	1,  // 9: rpc.HealthCheckResponse.status:type_name -> rpc.HealthStatus
	2,  // 10: rpc.GetMethodsResponse.methods:type_name -> rpc.RPCMethod
	3,  // 11: rpc.GenericService.Call:input_type -> rpc.RPCRequest
	5,  // 12: rpc.GenericService.HealthCheck:input_type -> rpc.HealthCheckRequest
	14, // 13: rpc.GenericService.GetMethods:input_type -> google.protobuf.Empty
	4,  // 14: rpc.GenericService.Call:output_type -> rpc.RPCResponse
	6,  // 15: rpc.GenericService.HealthCheck:output_type -> rpc.HealthCheckResponse
	7,  // 16: rpc.GenericService.GetMethods:output_type -> rpc.GetMethodsResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_rpc_proto_service_proto_init() }
func file_pkg_rpc_proto_service_proto_init() {
	if File_pkg_rpc_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_proto_service_proto_rawDesc), len(file_pkg_rpc_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_proto_service_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_proto_service_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_proto_service_proto_msgTypes,
	}.Build()
	File_pkg_rpc_proto_service_proto = out.File
	file_pkg_rpc_proto_service_proto_goTypes = nil
	file_pkg_rpc_proto_service_proto_depIdxs = nil
}
