#!/bin/bash

# Simple client for testing the job creation API

# Default values
API_URL="http://localhost:9002/api/jobs"  # Corrected URL with /api prefix
DEFAULT_PAYLOAD='[{
  "user_address": "0x1234567890abcdef1234567890abcdef12345678",
  "stake_amount": 1000000000000000000,
  "token_amount": 1000000000000000000,
  "task_definition_id": 1,
  "priority": 1,
  "security": 1,
  "time_frame": 3600,
  "recurring": false,
  "time_interval": 300,
  "trigger_chain_id": "1",
  "trigger_contract_address": "0x1234567890abcdef1234567890abcdef12345678",
  "trigger_event": "Transfer(address,address,uint256)",
  "script_ipfs_url": "ipfs://Qm123456789",
  "script_trigger_function": "trigger",
  "target_chain_id": "1",
  "target_contract_address": "0x1234567890abcdef1234567890abcdef12345678",
  "target_function": "execute",
  "arg_type": 0,
  "arguments": ["arg1", "arg2"],
  "script_target_function": "execute"
}]'

# Help message
show_help() {
  echo "Usage: $0 [options]"
  echo
  echo "Options:"
  echo "  -u, --url URL       API URL (default: $API_URL)"
  echo "  -j, --job-id ID     Job ID (default: auto-generated by server)"
  echo "  -a, --address ADDR  User wallet address (default: 0x1234...5678)"
  echo "  -f, --file FILE     Path to JSON payload file"
  echo "  -h, --help          Show this help message"
  echo
  echo "Example:"
  echo "  $0 --address 0xYourAddress"
  echo "  $0 --file mypayload.json"
}

# Parse command line arguments
while (( "$#" )); do
  case "$1" in
    -u|--url)
      API_URL="$2"
      shift 2
      ;;
    -j|--job-id)
      JOB_ID="$2"
      shift 2
      ;;
    -a|--address)
      USER_ADDRESS="$2"
      shift 2
      ;;
    -f|--file)
      PAYLOAD_FILE="$2"
      shift 2
      ;;
    -h|--help)
      show_help
      exit 0
      ;;
    *)
      echo "Error: Unsupported flag $1" >&2
      show_help
      exit 1
      ;;
  esac
done

# Prepare payload
if [[ -n "$PAYLOAD_FILE" && -f "$PAYLOAD_FILE" ]]; then
  PAYLOAD=$(<"$PAYLOAD_FILE")
elif [[ -n "$USER_ADDRESS" ]]; then
  # Replace address in default payload
  PAYLOAD=$(echo "$DEFAULT_PAYLOAD" | sed "s/\"user_address\": \"[^\"]*\"/\"user_address\": \"$USER_ADDRESS\"/")
else
  PAYLOAD="$DEFAULT_PAYLOAD"
fi

# Make API request
echo "Making request to: $API_URL"
echo "Payload: $PAYLOAD"
echo

curl -X POST "$API_URL" \
  -H "Content-Type: application/json" \
  -d "$PAYLOAD" \
  -v

echo -e "\n\nRequest complete!" 