name: Go Dependencies

on:
  push:
    branches:
      - dev
  pull_request:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday
  workflow_dispatch:  # Allow manual triggers

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for the action to work properly
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Install go-mod-outdated
        run: go install github.com/psampaz/go-mod-outdated@latest

      - name: Check for updates
        id: check_updates
        run: |
          # Save the output to a file
          go list -u -m -json all | go-mod-outdated -update -direct > outdated.txt
          
          # Check if there are any updates
          if [ -s outdated.txt ]; then
            echo "updates_available=true" >> $GITHUB_OUTPUT
            # Run go get to update dependencies
            go get -u ./...
            go mod tidy
          else
            echo "updates_available=false" >> $GITHUB_OUTPUT
          fi
    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): update Go dependencies"
          branch: "update-go-dependencies"
          commit-message: "chore(deps): update Go dependencies"
          body: "Automated dependency updates.\nPlease review the changes before merging."
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "5kyguy <167390221+5kyguy@users.noreply.github.com>"
